# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

required_plugins = %w( vagrant-vbguest )

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vbguest.installer_arguments = %w{--nox11}

  config.vm.define :server do |srv|
    srv.vm.hostname = "nagios-server"
    srv.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
      # https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
    config.vm.synced_folder "../provision/", "/home/vagrant/provision"
    srv.vm.network "forwarded_port", guest: 80, host: 8080
    srv.vm.network "private_network", ip: "192.168.199.10", virtualbox__intnet: "vagrant-intnet"
    srv.vm.provision "shell", path: "server-provision"
  end

  config.vm.define :client do |clnt|
    clnt.vm.hostname = "nagios-client"
    clnt.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
    config.vm.synced_folder "../provision/", "/home/vagrant/provision"
    clnt.vm.network "private_network", ip: "192.168.199.11", virtualbox__intnet: "vagrant-intnet"
    clnt.vm.provision "shell", path: "client-provision"
  end
end
