Vagrant.configure("2") do |config|

  config.vm.define :"isp" do |isp|
    isp.vm.box = "cheretbe/routeros-long-term"
    isp.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    end
    isp.vm.network "private_network", virtualbox__intnet: "vagrant-isp", auto_config: false

    isp.vm.provision "routeros_file", name: "Upload provison script",
      source: "isp_provision.rsc", destination: "isp_provision.rsc"
    isp.vm.provision "routeros_command", name: "Provision",
      command: "/import isp_provision.rsc", check_script_error: true
  end
end