---
- name: Router box provision
  hosts: all

  tasks:
    - name: Print host information
      debug:
        msg: "{{ ansible_fqdn }}: {{ ansible_distribution }} {{ ansible_distribution_version}}"

    # - import_role: name=/host_home/projects/ansible-playbooks/purevpn-ovpn-client
    # - import_role: name=/host_home/projects/ansible-playbooks/router
    - import_role: name=/opt/ansible-playbooks/purevpn-ovpn-client
    - import_role: name=/opt/ansible-playbooks/router
