Vagrant.configure("2") do |config|
  config.vm.box = "cheretbe/routeros7"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
  end
  config.vm.provision "routeros_command", name: "Internet access via host NAT",
    command: '/ip dhcp-client set [find interface="host_nat"] use-peer-dns=yes add-default-route=yes'
end
