---
- name: Linux box provision
  hosts: all

  tasks:
    - name: Print host information
      debug:
        msg: "{{ ansible_fqdn }}: {{ ansible_distribution }} {{ ansible_distribution_version}}"

    - name: Update /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.80.32 win10
      become: yes
