#!/bin/bash

set -euo pipefail

# -L   Follow redirects
# -s   Silent mode. Don't output anything
curl -L -s https://github.com/cheretbe/vagrant-files/raw/master/linux/provision/centos-provision.sh -o - | bash

curl -L -s https://github.com/cheretbe/vagrant-files/raw/master/linux/provision/two-hosts-provision.sh -o - | bash