# -*- mode: ruby -*-
# vi: set ft=ruby :

required_plugins = %w( vagrant-vbguest )

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

Vagrant.configure("2") do |config|
  config.vbguest.installer_arguments = %w{--nox11}

  config.vm.define :host1 do |host1|
    host1.vm.box = "centos/7"
    host1.vm.hostname = "host1"
    host1.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    end
    host1.vm.synced_folder ".", "/home/vagrant/sync", disabled: true
    host1.vm.network "private_network", ip: "192.168.199.10", virtualbox__intnet: "vagrant-intnet"
    host1.vm.provision "shell", path: "centos-provision"
  end

  config.vm.define :host2 do |host2|
    host2.vm.box = "centos/7"
    host2.vm.hostname = "host2"
    host2.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    end
    host2.vm.synced_folder ".", "/home/vagrant/sync", disabled: true
    host2.vm.network "private_network", ip: "192.168.199.11", virtualbox__intnet: "vagrant-intnet"
    host2.vm.provision "shell", path: "centos-provision"
  end
end
