# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../provision/common.rb"
require_relative "../../host-scripts/common.rb"

Vagrant.configure("2") do |config|
  config.vm.define :central_isp do |central_isp|
    central_isp.vm.box = "cheretbe/routeros"
    central_isp.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    end
    central_isp.vm.network "private_network", virtualbox__intnet: "vagrant-inter_isp", auto_config: false
    central_isp.vm.network "private_network", virtualbox__intnet: "vagrant-central_isp", auto_config: false

    central_isp.trigger.after :up, :provision, :reload, :resume do |trigger|
      trigger.ruby do |env,machine|
        if machine.custom_provision_enabled then
          # [!] 0-based vm_NIC_mac_addresses array should be initialized at this point
          # by the original Vagrantfile
          system("vagrant", "ssh", "#{machine.name}", "--",
            ":global interIspMACaddr \"" + machine.vm_NIC_mac_addresses[2] + "\"; " +
            ":global centralIspMACaddr \"" + machine.vm_NIC_mac_addresses[3] + "\""
          )
          upload_mikrotik_script(machine, "central_isp_provision.rsc", "central_isp_provision")
          system "vagrant ssh #{machine.name} -- /system script run central_isp_provision"
        end
      end
    end
  end

  config.vm.define :pregol_isp do |pregol_isp|
    pregol_isp.vm.box = "cheretbe/routeros"
    pregol_isp.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    end
    pregol_isp.vm.network "private_network", virtualbox__intnet: "vagrant-inter_isp", auto_config: false
    pregol_isp.vm.network "private_network", virtualbox__intnet: "vagrant-pregol_isp", auto_config: false

    pregol_isp.trigger.after :up, :provision, :reload, :resume do |trigger|
      trigger.ruby do |env,machine|
        if machine.custom_provision_enabled then
          # [!] 0-based vm_NIC_mac_addresses array should be initialized at this point
          # by the original Vagrantfile
          system("vagrant", "ssh", "#{machine.name}", "--",
            ":global interIspMACaddr \"" + machine.vm_NIC_mac_addresses[2] + "\"; " +
            ":global pregolIspMACaddr \"" + machine.vm_NIC_mac_addresses[3] + "\""
          )
          upload_mikrotik_script(machine, "pregol_isp_provision.rsc", "pregol_isp_provision")
          system "vagrant ssh #{machine.name} -- /system script run pregol_isp_provision"
        end
      end
    end
  end

  config.vm.define :pregol_router do |pregol_router|
    pregol_router.vm.box = "cheretbe/routeros"
    pregol_router.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    end
    pregol_router.vm.network "private_network", virtualbox__intnet: "vagrant-pregol_isp", auto_config: false
    pregol_router.vm.network "private_network", virtualbox__intnet: "vagrant-pregol_lan", auto_config: false

    pregol_router.trigger.after :up, :provision, :reload, :resume do |trigger|
      trigger.ruby do |env,machine|
        if machine.custom_provision_enabled then
          # [!] 0-based vm_NIC_mac_addresses array should be initialized at this point
          # by the original Vagrantfile
          system("vagrant", "ssh", "#{machine.name}", "--",
            ":global pregolIspMACaddr \"" + machine.vm_NIC_mac_addresses[2] + "\"; " +
            ":global pregolLanMACaddr \"" + machine.vm_NIC_mac_addresses[3] + "\""
          )
          upload_mikrotik_script(machine, "pregol_router_provision.rsc", "pregol_router_provision")
          system "vagrant ssh #{machine.name} -- /system script run pregol_router_provision"
        end
      end
    end
  end
end