# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../provision/common.rb"

Vagrant.configure("2") do |config|
  config.vm.define :client do |mt_client|
    mt_client.vm.box = "cheretbe/routeros"
    mt_client.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    end
    mt_client.vm.network "private_network", virtualbox__intnet: "vagrant-isp1-intnet", auto_config: false
    mt_client.vm.network "private_network", virtualbox__intnet: "vagrant-isp2-intnet", auto_config: false

    config.vm.provision "trigger", :option => "value" do |trigger|
      trigger.fire do
        upload_file("mt_client_provision.rsc", "mt_client_provision.rsc", "mt_client_provision")
        run "vagrant ssh -- /system script run mt_client_provision"
      end
    end
  end
end