---

- name: Windows box provision
  hosts: all

  tasks:
    - name: Print host information
      debug:
        msg: "{{ ansible_fqdn }}: {{ ansible_distribution }} {{ ansible_distribution_version}}"

    - name: install Google Chrome browser
      win_chocolatey:
        name: googlechrome
        state: present
        ignore_checksums: yes

    - name: install Mozilla Firefox browser
      win_chocolatey:
        name: firefox
        state: present

    - name: Add 'uBlock Origin' extension to Google Chrome
      win_regedit:
        path: HKLM:\SOFTWARE\WOW6432Node\Google\Chrome\Extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm
        name: update_url
        data: https://clients2.google.com/service/update2/crx

    - name: Add 'Selection Search' extension to Google Chrome
      win_regedit:
        path: HKLM:\SOFTWARE\WOW6432Node\Google\Chrome\Extensions\gipnlpdeieaidmmeaichnddnmjmcakoe
        name: update_url
        data: https://clients2.google.com/service/update2/crx
