require File.expand_path("../../../lib/host_functions.rb", __FILE__)

local_settings = read_local_settings_new([
  {"name" => "cpu", "default" => "2"},
  {"name" => "memory", "default" => "4096"},
])


Vagrant.configure("2") do |config|
  config.vm.box = "cheretbe/win10_gui"
  apply_standard_settings(config, "default", local_settings)
end
