Vagrant.configure("2") do |config|
  config.vm.define "win10" do |win10|
    win10.vm.box = "cheretbe/win10ltsc2019_ru_64"
    win10.winrm.username = "vagrant"
    win10.winrm.password = "#{ENV['AO_DEFAULT_VAGRANT_PASSWORD']}"
    win10.vm.boot_timeout = 900

    win10.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "2"
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end

    win10.vm.network "private_network", ip: "172.24.0.11", virtualbox__intnet: "vagrant-intnet"
  end

  config.vm.define :"ansible-controller" do |ansible_controller|
    ansible_controller.vm.box = "ubuntu/focal64"
    ansible_controller.vm.hostname = "ansible-controller"
    ansible_controller.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    end
    ansible_controller.vm.network "private_network", ip: "172.24.0.10", virtualbox__intnet: "vagrant-intnet"
    ansible_controller.vm.provision "shell",
      keep_color: true,
      inline: <<-SHELL
        set -euo pipefail
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get -yq install ansible
        ansible-galaxy collection install community.windows
      SHELL
      ansible_controller.vm.provision "ansible_local" do |ansible|
        ansible.install = false
        ansible.playbook = "provision.yml"
        ansible.extra_vars = {
          ansible_password: "#{ENV['AO_DEFAULT_VAGRANT_PASSWORD']}",
        }
        ansible.inventory_path = "inventory.yml"
        ansible.limit = "win10"
      end
  end
end
