require File.expand_path("../../../lib/host_functions.rb", __FILE__)

local_settings = read_local_settings_new([
  {"name" => "cpu", "default" => "2"},
  {"name" => "memory", "default" => "2048"},
])

Vagrant.configure("2") do |config|
  # Canonical will no longer publish Vagrant images directly starting with Ubuntu 24.04 LTS (Noble Numbat)
  # https://documentation.ubuntu.com/public-images/en/latest/public-images-explanation/vagrant/#support
  # https://github.com/chef/bento
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "ubuntu-noble-vm"
  apply_standard_settings(config, "default", local_settings)
end
