Vagrant.configure("2") do |config|

  config.vm.define :"vpn-client" do |vpn_client|
    vpn_client.vm.box = "cheretbe/routeros-long-term"
    vpn_client.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    end
    vpn_client.vm.network "private_network", virtualbox__intnet: "vpn-client-lan", auto_config: false

    vpn_client.vm.provision "routeros_file", name: "Upload provison script",
      source: "vpn_client_provision.rsc", destination: "vpn_client_provision.rsc"
    vpn_client.vm.provision "routeros_command", name: "Provision",
      command: "/import vpn_client_provision.rsc", check_script_error: true
  end
end