Vagrant.configure("2") do |config|

  config.vm.define :"vpn-client" do |vpn_client|
    vpn_client.vm.box = "cheretbe/win10ltsc2019_ru_64"
    vpn_client.winrm.username = "vagrant"
    vpn_client.winrm.password = "#{ENV['AO_DEFAULT_VAGRANT_PASSWORD']}"
    vpn_client.vm.boot_timeout = 900
    vpn_client.vm.network "private_network", ip: "192.168.1.10", virtualbox__intnet: "vpn-client-lan"

    vpn_client.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end

    # vpn_client.vm.provision "ansible" do |ansible|
    #   ansible.playbook = "provision.yml"
    #   ansible.extra_vars = {
    #     "ansible_winrm_scheme": "http"
    #   }
    # end
  end

  config.vm.define :"client-router" do |client_router|
    client_router.vm.box = "cheretbe/routeros-long-term"
    client_router.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    end
    client_router.vm.network "private_network", virtualbox__intnet: "vpn-client-lan", auto_config: false

    client_router.vm.provision "routeros_file", name: "Upload provison script",
      source: "client_router_provision.rsc", destination: "client_router_provision.rsc"
    client_router.vm.provision "routeros_command", name: "Provision",
      command: "/import client_router_provision.rsc", check_script_error: true
  end
end