Vagrant.configure("2") do |config|

  config.vm.define :"vpn-client" do |vpn_client|
    config.vm.box = "cheretbe/win10ltsc2019_ru_64"
    config.winrm.username = "vagrant"
    config.winrm.password = "#{ENV['AO_DEFAULT_VAGRANT_PASSWORD']}"
    config.vm.boot_timeout = 900
    config.vm.network "private_network", ip: "192.168.1.10", virtualbox__intnet: "vpn-client-lan"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end

    # config.vm.provision "ansible" do |ansible|
    #   ansible.playbook = "provision.yml"
    #   ansible.extra_vars = {
    #     "ansible_winrm_scheme": "http"
    #   }
    # end
  end

  # config.vm.define :"vpn-client" do |vpn_client|
  #   vpn_client.vm.box = "cheretbe/routeros-long-term"
  #   vpn_client.vm.provider "virtualbox" do |vb|
  #     vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
  #   end
  #   vpn_client.vm.network "private_network", virtualbox__intnet: "vpn-client-lan", auto_config: false

  #   vpn_client.vm.provision "routeros_file", name: "Upload provison script",
  #     source: "vpn_client_provision.rsc", destination: "vpn_client_provision.rsc"
  #   vpn_client.vm.provision "routeros_command", name: "Provision",
  #     command: "/import vpn_client_provision.rsc", check_script_error: true
  # end
end