require File.expand_path("../../../lib/host_functions.rb", __FILE__)

if not ENV.has_key?('AO_DEFAULT_VAGRANT_PASSWORD')
  abort "This Vagrantfile needs AO_DEFAULT_VAGRANT_PASSWORD environment variable to be defined. Aborting"
end

local_settings = read_local_settings_new([
  {"name" => "cpus", "default" => "2"},
  {"name" => "memory", "default" => "2048"},
  {"name" => "cpus.seafile-client", "default" => "1"},
  {"name" => "memory.seafile-client", "default" => "2048"},
  {"name" => "memory.win10", "default" => "4096"},
  {"name" => "common_repo_source", "default" => "master"}
])

Vagrant.configure("2") do |config|

  define_ansible_controller(
    config=config,
    ip="192.168.80.40",
    common_repo_source: local_settings["common_repo_source"]
  )

  config.vm.define :"seafile-server" do |seafile_server|
    # seafile_server.vm.box = "ubuntu/focal64"
    seafile_server.vm.box = "ubuntu/jammy64"
    seafile_server.vm.hostname = "seafile.local.test"

    apply_standard_settings(seafile_server, "seafile-server", local_settings)

    seafile_server.vm.network "private_network", virtualbox__intnet: "vagrant-intnet", ip: "192.168.80.41"
    seafile_server.vm.network "forwarded_port", guest: 80, host: 8080

    seafile_server.vm.provision "shell", name: "Enable cleartext passwords for SSH",
      keep_color: true,
      inline: <<-SHELL
        set -euo pipefail
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        systemctl restart sshd
      SHELL

    ansible_provision seafile_server,
      playbook="seafile_server_provision.yml",
      extra_vars: {
        "seafile_version": "9.0.13",
        "docker_ce_registry_proxy": ENV["AO_VAGRANT_DOCKER_PROXY"] || false
      }
  end

  config.vm.define :"seafile-client" do |seafile_client|
    seafile_client.vm.box = "ubuntu/jammy64"
    seafile_client.vm.hostname = "seafile-client.local.test"

    apply_standard_settings(seafile_client, "seafile-client", local_settings)

    seafile_client.vm.network "private_network", virtualbox__intnet: "vagrant-intnet", ip: "192.168.80.42"

    seafile_client.vm.provision "shell", name: "Enable cleartext passwords for SSH",
      keep_color: true,
      inline: <<-SHELL
        set -euo pipefail
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        systemctl restart sshd
      SHELL

    ansible_provision seafile_client,
      playbook="seafile_client_provision.yml"
  end

  config.vm.define "win10", autostart: false do |win10|
    win10.vm.box = "cheretbe/win10_gui"

    apply_standard_settings(win10, "win10", local_settings)

    win10.vm.network "private_network", virtualbox__intnet: "vagrant-intnet", ip: "192.168.80.43"

    ansible_provision win10,
      playbook="win_provision.yml",
      extra_vars: {
        "ansible_password": "#{ENV['AO_DEFAULT_VAGRANT_PASSWORD']}"
      }
  end
end
