---
- name: devpi provision
  hosts: all
  become: yes

  tasks:
    - name: Add 'vagrant' user to 'vboxsf' group
      user:
        name: vagrant
        groups: vboxsf
        append: yes

    - name: Install devpi PIP package
      pip:
        name: devpi
        executable: pip3
      become: true

    - name: Init devpi config for user vagrant
      # become_user is not enough, we need su with a login shell to
      # apply vboxsf group asignment
      command: su -l - vagrant -c "devpi-init --serverdir /media/sf_cache/devpi"
      # become_user: vagrant 
      args:
        creates: /media/sf_cache/devpi

    - name: Copy devpi service unit file
      copy:
        src: devpi.service
        dest: /etc/systemd/system
        owner: root
        group: root
      notify:
        - Start 'devpi' service


  handlers:
    - name: Start 'devpi' service
      systemd:
        name: devpi
        state: restarted
        enabled: yes
        daemon_reload: yes
