---
- name: devpi provision
  hosts: all
  become: yes

  tasks:
    - name: Add 'vagrant' user to 'vboxsf' group
      user:
        name: vagrant
        groups: vboxsf
        append: yes

    - name: Install devpi PIP package
      pip:
        name: devpi
        executable: pip3
      become: true

    - name: Init devpi config for user vagrant
      # command: su - vagrant -c "devpi-init"
      command: devpi-init --serverdir /media/sf_cache/devpi
      become_user: vagrant
      args:
        creates: /media/sf_cache/devpi

    - name: Make sure '/media/sf_cache/devpi' directory exists
      file:
        path: /media/sf_cache/devpi
        state: directory

    - name: Copy devpi service unit file
      copy:
        src: devpi.service
        dest: /etc/systemd/system
        owner: root
        group: root
      notify:
        - Start 'devpi' service

  #   - name: Create drop-in file for 'apt-cacher-ng' service
  #     copy:
  #       content: |
  #         [Unit]
  #         RequiresMountsFor=/media/sf_cache/apt-cacher-ng
  #       dest: /etc/systemd/system/apt-cacher-ng.service.d/override.conf
  #       mode: 0644
  #       owner: root
  #       group: root
  #     notify: Restart 'apt-cacher-ng' service


  handlers:
    - name: Start 'devpi' service
      systemd:
        name: devpi
        state: restarted
        enabled: yes
        daemon_reload: yes
