require File.expand_path("../../../lib/host_functions.rb", __FILE__)

check_env_variables(
  mandatory_vars: ["TF_VAR_yc_token"],
  optional_vars:["TF_VAR_cf_api_token"]
)

local_settings = read_local_settings_new([
  {"name" => "cpus", "default" => "2"},
  {"name" => "memory", "default" => "2048"},
  {"name" => "common_repo_source", "default" => "master"}
])


Vagrant.configure("2") do |config|
  define_ansible_controller(
    config=config,
    ip="192.168.80.70",
    common_repo_source: local_settings["common_repo_source"]
  )

  config.vm.define :"terraform" do |terraform|
    terraform.vm.box = "ubuntu/jammy64"
    terraform.vm.hostname = "terraform"

    apply_standard_settings(terraform, "terraform", local_settings)

    terraform.vm.network "private_network", virtualbox__intnet: "vagrant-intnet", ip: "192.168.80.71"

    enable_ssh_clear_text_passwords(terraform)

    ansible_provision terraform,
      playbook="terraform_provision.yml",
      extra_vars: {
        TF_VAR_yc_token: ENV["TF_VAR_yc_token"],
        TF_VAR_cf_api_token: ENV["TF_VAR_cf_api_token"] || nil
      }
  end
end
