Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
  end
  config.vm.network "private_network", ip: "192.168.199.12", virtualbox__intnet: "vagrant-domain"
  config.vm.provision "shell", name: "Provision template",
    keep_color: true, # privileged: false,
    inline: <<-SHELL
      set -euo pipefail
      uname -a
    SHELL

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provision/provision.yml"
    ansible.compatibility_mode = "2.0"
    ansible.extra_vars = {
      "ansible_python_interpreter": "/usr/bin/python3"
    }
  end
end
