---
# - name: Setup common parameters
#   import_playbook: /opt/ansible-playbooks/linux_server_setup.yml

- name: Terraform box provision
  hosts: all

  tasks:
    - name: Print host information
      debug:
        msg: "{{ ansible_fqdn }}: {{ ansible_distribution }} {{ ansible_distribution_version}}"

    - name: Fix multipath daemon error spamming system log
      blockinfile:
        path: /etc/multipath.conf
        block: |
          blacklist {
            device {
              vendor "VBOX"
              product "HARDDISK"
            }
          }
      become: yes
      notify: Restart multipath daemon

    - name: Add HashiCorp repository key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
      become: yes

    - name: Add HashiCorp repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
      become: yes

    - name: Install Terraform package
      apt:
        name: terraform
        update_cache: true
        cache_valid_time: "{{ '1d' | community.general.to_seconds | int }}"
      become: yes

    - name: Create ansible config file
      become: true
      ansible.builtin.copy:
        dest: /home/vagrant/ansible.cfg
        content: |
          # Generated by Ansible at {{ lookup('pipe', 'hostname -f') }}
          [defaults]
          inventory = inventory.yml
          host_key_checking = False
          bin_ansible_callbacks = True
          stdout_callback = yaml
        mode: "0644"
        owner: vagrant
        group: vagrant
      delegate_to: localhost

    - name: Copy ansible inventory file
      ansible.builtin.copy:
        src: inventory.yml
        dest: /home/vagrant/inventory.yml
        owner: vagrant
        group: vagrant
        mode: '0644'
      delegate_to: localhost

    - name: Make sure /home/vagrant/host_vars exists
      ansible.builtin.file:
        state: directory
        path: /home/vagrant/host_vars
        owner: vagrant
        group: vagrant
        mode: 0775
      delegate_to: localhost

    - name: Create vars file for terraform host
      vars:
        _vars_file_content:
          terraform_projects:
            speedtest-yacloud:
              terraform_vars:
                yc_token: "{{ TF_VAR_yc_token }}"
                cf_api_token: "{{ TF_VAR_cf_api_token }}"
              local_backend_path: /host_home/Documents/data/terrorm_states/speedtest-yacloud
      ansible.builtin.copy:
        content: "{{ _vars_file_content | to_nice_yaml }}"
        dest: /home/vagrant/host_vars/terraform.yml
        owner: vagrant
        group: vagrant
        mode: 0640
      delegate_to: localhost

  handlers:
    - name: Restart multipath daemon
      ansible.builtin.systemd:
        name: multipathd
        state: restarted
      become: yes