# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../../host-scripts/common.rb"

required_plugins = %w( vagrant-triggers )

# For automatic installation see
# https://github.com/cheretbe/notes/blob/master/vagrant.md#automatic-plugins-installation
plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "This Vagrantfile needs one or more additional plugins to be installed: #{plugins_to_install.join(', ')}"
  puts "Use the following command:\n\n"
  puts "vagrant plugin install #{plugins_to_install.join(' ')}\n\n"
  abort "Installation of one or more additional plugins needed. Aborting."
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  config.vm.network "public_network", ip: "192.168.99.10"
  config.vm.provision "shell", path: "../../linux/provision/ubuntu-provision.sh"
  config.vm.provision "shell", path: "../../linux/provision/vb-guest-additions-provision.sh"
  config.vm.provision "file", source: "provision.sh", destination: "provision.sh"
  config.vm.provision "trigger", :option => "value" do |trigger|
    trigger.fire do
      run_remote  "/bin/bash /home/vagrant/provision.sh #{get_vb_nic_mac_address(2)}"
    end
  end
end