Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "burp-client"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    # Disconnecting COM port fails on Vagrant 2.2.9 + VirtualBox 6.1.12
    # https://github.com/hashicorp/vagrant/issues/11626
    # vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
  end
  config.vm.network "private_network", ip: "172.24.0.11", virtualbox__intnet: "vagrant-burp"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provision/provision.yml"
    ansible.compatibility_mode = "2.0"
    ansible.extra_vars = {
      "ansible_python_interpreter": "/usr/bin/python3"
    }
  end
end
