#!/bin/bash

set -e

# Disable SELinux
setenforce 0
sed -i s/SELINUX=enforcing/SELINUX=disabled/g /etc/selinux/config

yum update -y
yum install -y epel-release
yum install -y mc nano wget net-tools htop