# -*- mode: ruby -*-
# vi: set ft=ruby :

required_plugins = %w( vagrant-vbguest )

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

Vagrant.configure("2") do |config|
  config.vbguest.installer_arguments = %w{--nox11}

  config.vm.box = "centos/7"
  # config.vm.hostname = "nagios-server"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
  end
  config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true
  config.vm.synced_folder "../provision/", "/home/vagrant/provision"
  # config.vm.network "private_network", ip: "192.168.199.10", virtualbox__intnet: "vagrant-intnet"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision "shell", path: "provision-script"
end
