---
- name: Seafile server provision
  hosts: all

  tasks:
    - name: Print host information
      debug:
        msg: "{{ ansible_fqdn }}: {{ ansible_distribution }} {{ ansible_distribution_version}}"

    - name: Make sure /root/.docker exists
      ansible.builtin.file:
        state: directory
        path: /root/.docker
        owner: root
        group: root
        mode: 0750
      become: true

    # We don't use community.docker.docker_login because docker is not yet installed at this point
    - name: Add credentials for docker.seadrive.org
      ansible.builtin.copy:
        # https://customer.seafile.com/downloads/
        # seafile:zjkmid6rQibdZ=uJMuWS
        content: |
          {
            "auths": {
              "docker.seadrive.org": {
                "auth": "c2VhZmlsZTp6amttaWQ2clFpYmRaPXVKTXVXUw=="
              }
            }
          }
        dest: /root/.docker/config.json
        mode: 0640
      become: true

- name: Include docker_compose_services playbook
  ansible.builtin.import_playbook: /opt/ansible-playbooks/docker_compose_services.yml
