---
- name: Linux box provision
  hosts: all

  tasks:
    - name: Print host information
      debug:
        msg: "{{ ansible_fqdn }}: {{ ansible_distribution }} {{ ansible_distribution_version}}"

    - name: Checkout shared docker configs repo
      ansible.builtin.git:
        repo: "https://github.com/cheretbe/docker-configs.git"
        dest: "/opt/docker-configs"
      become: true

    - include_role: name="/opt/ansible-playbooks/docker-ce"
      vars:
        docker_ce_users: ["vagrant"]

    - name: Add credentials for docker.seadrive.org
      community.docker.docker_login:
        registry_url: docker.seadrive.org
        username: seafile
        password: zjkmid6rQibdZ=uJMuWS

    # As of 13.01.23 'docker_compose' module has a requirement: docker-compose >= 1.7.0, < 2.0.0
    # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html#ansible-collections-community-docker-docker-compose-module-requirements
    # Therefore docker compose plugin v2.14.1, installed by 'docker-ce' role,
    # can't be used. We need to install separate docker-compose binary and will
    # use pip for it
    - name: Install packages
      ansible.builtin.apt:
        name: ["python3-pip"]
        update_cache: true
        cache_valid_time: "{{ '1day' | community.general.to_seconds | int }}"
      become: true

    - name: Install PIP modules
      ansible.builtin.pip:
        name: docker-compose
      become: true

    - name: Create and start Docker containers
      community.docker.docker_compose:
        project_src: /opt/docker-configs/seafile
