---
- name: Ansible provision template
  hosts: all
  become: yes

# Shared repo checkout and pip packages example:
# https://github.com/cheretbe/notes/blob/master/vagrant.md#ansible-provision
  tasks:
    - name: Sample task
      debug:
        msg: "{{ ansible_fqdn }}: {{ ansible_distribution }} {{ ansible_distribution_version}}"