---
- name: Ansible provision template
  hosts: all
  become: yes

# Shared repo checkout and pip packages example:
# https://github.com/cheretbe/notes/blob/master/vagrant.md#ansible-provision
  tasks:
    - name: Show box info
      debug:
        msg: "{{ ansible_fqdn }}: {{ ansible_distribution }} {{ ansible_distribution_version}}"

    - name: Checkout shared playbooks repo
      git:
        repo: "https://github.com/cheretbe/ansible-playbooks.git"
        dest: "/ansible-playbooks"

    - include_role: name="/ansible-playbooks/linux-dns"