---
- name: Linux domain member provision
  hosts: all
  become: yes

# Shared repo checkout and pip packages example:
# https://github.com/cheretbe/notes/blob/master/vagrant.md#ansible-provision
  tasks:
    - name: Show box info
      debug:
        msg: "{{ ansible_fqdn }}: {{ ansible_distribution }} {{ ansible_distribution_version}}"

    - name: Checkout shared playbooks repo
      git:
        repo: "https://github.com/cheretbe/ansible-playbooks.git"
        dest: "/ansible-playbooks"

    - include_role: name="/ansible-playbooks/apt-wait-for-unlock"
    - include_role: name="/ansible-playbooks/linux-utils"
    - include_role: name="/ansible-playbooks/linux-locale"
    - include_role: name="/ansible-playbooks/linux-dns"

    - name: Install apt packages
      apt:
        name: [samba, krb5-user, winbind, libnss-winbind, libpam-winbind]
        # Fix for warning message "Could not find aptitude. Using apt-get instead"
        force_apt_get: yes
        update_cache: no

    - name: Write custom /etc/samba/smb.conf
      template:
        src: etc_samba_smb.conf.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
      # register: smb_conf_update
      notify: Restart Samba services

    - name: Write custom /etc/krb5.conf
      template:
        src: etc_krb5.conf.j2
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: 0644
        backup: yes

    - name: Check domain membership
      command: "/usr/bin/net ads testjoin"
      changed_when: false
      failed_when: false
      register: domain_membership

    - name: Join domain
      command: "/usr/bin/net ads join -U 'test%`1q`1q`1q' createcomputer=ou_test/computers_test"
      changed_when: false
      when: domain_membership.rc != 0
      notify: Restart Samba services

    - name: Configure pam_mkhomedir
      pamd:
        name: common-session
        type: session
        control: required
        module_path: pam_mkhomedir.so
        module_arguments: "skel=/etc/skel umask=0077"
        state: updated

  handlers:
    - name: Restart Samba services
      service:
        name: "{{ item }}"
        state: restarted
      with_items: [winbind, smbd, nmbd]
