if Vagrant::Util::Platform.windows?
  ifInfo = %x("C:/Program Files/Oracle/VirtualBox/VBoxManage.exe" list bridgedifs)
else
  ifInfo = %x(VBoxManage list bridgedifs)
end
parsed_name = ""
available_bridges = []
ifInfo.split("\n").each do |info_line|
  unless info_line.empty?
    info_name, info_value = info_line.split(":", 2)
    info_value.strip!
    if info_name == "Name" then parsed_name = info_value end
    if (info_name == "Status") and (info_value == "Up") and (not parsed_name.empty?) then
      available_bridges << parsed_name
    end
  end
end
if available_bridges.length == 0 then
   abort "ERROR: Couldn't find active bridged network interfaces"
elsif
  network_bridge = available_bridges[0]
else
  # TODO: add local config file option to auto-select an adapter
  abort "ERROR: More than one active bridged network interface found"
end


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    vb.memory = "2048"
    vb.customize ["sharedfolder", "add", :id, "--name", "cache",
      "--hostpath", File.expand_path("./cache", File.dirname(__FILE__)),
      "--automount"]
  end
  config.vm.network "public_network", bridge: network_bridge
  config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vboxsf",
    mount_options: ["dmode=775,fmode=664"]

  config.vm.provision "shell",
    name: "Ansible installation using pip3",
    keep_color: true, privileged: true,
    inline: <<-SHELL
      apt-get update
      apt-get upgrade -y -q
      apt-get install -y -q python3-pip
      pip3 install wheel ansible
    SHELL

  config.vm.provision "ansible_local" do |ansible|
    # ansible.install_mode = :pip
    ansible.playbook = "provision/provision_apt-cache-ng.yml"
    ansible.compatibility_mode = "2.0"
    ansible.extra_vars = {
      "ansible_python_interpreter": "/usr/bin/python3"
    }
  end
end
