# -*- mode: ruby -*-
# vi: set ft=ruby :

vagrant_file_dir = File.dirname(__FILE__)
provision_dir = File.expand_path("..", vagrant_file_dir) + "/provision"

if Vagrant::Util::Platform.windows? then
  #system('./generate_')
else
  system('../../host-scripts/generate_variables.sh ' + vagrant_file_dir + '/temp/set_variables.bat')
end

Vagrant.configure("2") do |config|
  config.vm.box = "cheretbe/win10_en_64"
  config.winrm.username = "vagrant"
  config.winrm.password = "#{ENV['AO_DEFAULT_VAGRANT_PASSWORD']}"
  config.vm.synced_folder "#{provision_dir}", "c:/users/vagrant/provision"
  # config.vm.provision "file", source: "temp/set_variables.bat", destination: "set_variables.bat"
  # config.vm.provision "shell", inline: "New-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Command Processor' -Name 'AutoRun' -Value 'c:\\users\\vagrant\\Documents\\set_variables.bat' -PropertyType ([Microsoft.Win32.RegistryValueKind]::String) -Force | Out-Null"
  # config.vm.provision "shell", path: "../provision/windows-config-builder.ps1", args: provision_param
  config.vm.provision "shell", inline: "& c:\\users\\vagrant\\provision\\windows-config-builder.bat"
end
