# -*- mode: ruby -*-
# vi: set ft=ruby :

vagrant_file_dir = File.dirname(__FILE__)
provision_dir = File.expand_path("..", vagrant_file_dir) + "/provision"

if Vagrant::Util::Platform.windows? then
  system('"../../host-scripts/generate_variables.bat" -resultFile "' + vagrant_file_dir + '/temp/env_variables.txt"')
else
  system('../../host-scripts/generate_variables.sh ' + vagrant_file_dir + '/temp/env_variables.txt')
end

if ENV['AO_PUBLISH_FILES_KEY_FILE'] != "" then
  if File.exist?(ENV["AO_PUBLISH_FILES_KEY_FILE"])
    FileUtils.cp(ENV["AO_PUBLISH_FILES_KEY_FILE"], "./temp/publish_files.key");
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "cheretbe/win10_en_64"
  config.winrm.username = "vagrant"
  config.winrm.password = "#{ENV['AO_DEFAULT_VAGRANT_PASSWORD']}"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end
  config.vm.boot_timeout = 600
  config.vm.synced_folder "#{provision_dir}", "c:/users/vagrant/provision"
  config.vm.provision "shell", inline: "& c:\\users\\vagrant\\provision\\windows-config-builder.ps1"
end
