---

- name: Windows box provision
  hosts: all

  tasks:
    - name: Print host information
      debug:
        msg: "{{ ansible_fqdn }}: {{ ansible_distribution }} {{ ansible_distribution_version}}"

    - name: install Google Chrome browser
      win_chocolatey:
        name: googlechrome
        state: present
        ignore_checksums: yes

    - name: Download Softether client
      win_get_url:
        url: https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.34-9744-beta/softether-vpnclient-v4.34-9744-beta-2020.03.20-windows-x86_x64-intel.exe
        dest: C:\Users\vagrant\Desktop\softether-vpnclient-v4.34-9744-beta-2020.03.20-windows-x86_x64-intel.exe
