require File.expand_path("../../../lib/host_functions.rb", __FILE__)

local_settings = read_local_settings_new([
  {"name" => "cpu", "default" => "2"},
  {"name" => "memory", "default" => "2048"},
])

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "debian-11-bullseye-vm"
  apply_standard_settings(config, "default", local_settings, apt_gpg_fix: true)
end
