require File.expand_path("../../../lib/host_functions.rb", __FILE__)

local_settings = read_local_settings_new([
  {"name" => "cpu", "default" => "2"},
  {"name" => "memory", "default" => "2048"},
  {"name" => "libvirt.machine_type", "default" => "pc-i440fx-jammy"},
  {"name" => "libvirt.host", "default" => ""},
  {"name" => "libvirt.connect_via_ssh", "default" => false},
  {"name" => "libvirt.username", "default" => ""},
  {"name" => "libvirt.id_ssh_key_file", "default" => ""},
  {"name" => "libvirt.storage_pool_name", "default" => "default"}
])

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "ubuntu-jammy-vm"
  # https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html
  config.vm.provider :libvirt do |libvirt|
    # libvirt.cpus = 1
    # libvirt.memory = 1024
    # qemu-system-x86_64 -machine help
    libvirt.machine_type = local_settings["libvirt.machine_type"]
    libvirt.cpu_mode = "host-passthrough"
    # https://github.com/cheretbe/notes/blob/master/linux/kvm.md#local-storage-pool
    libvirt.storage_pool_name = local_settings["libvirt.storage_pool_name"]

    if local_settings["libvirt.connect_via_ssh"]
      libvirt.host = local_settings["libvirt.host"]
      libvirt.connect_via_ssh = local_settings["libvirt.connect_via_ssh"]
      libvirt.username = local_settings["libvirt.username"]
      # Prepends $HOME/.ssh/ if no directory
      libvirt.id_ssh_key_file = local_settings["libvirt.id_ssh_key_file"]
    end
  end

  # config.vm.network :public_network, :dev => "enp0s31f6-br", :mode => "bridge", :type => "bridge"

  apply_standard_settings(config, "default", local_settings, no_synced_dirs: true)
end
