require File.expand_path("../../../lib/host_functions.rb", __FILE__)

local_settings = read_local_settings([
  {"name" => "common_repo_source", "default" => "master"}
])

Vagrant.configure("2") do |config|
  define_ansible_controller(
    config=config,
    ip="192.168.80.10",
    common_repo_source: local_settings.common_repo_source
  )

  config.vm.define :"server" do |server|
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "server"
    server.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      vb.customize ["modifyvm", :id, "--uart1", "off"]
      vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    end

    server.vm.network "private_network", ip: "192.168.80.11",
      virtualbox__intnet: "vagrant-intnet" #, mac: "080027840F13"
    server.vm.network "forwarded_port", guest: 80, host: 8081
    server.vm.network "forwarded_port", guest: 443, host: 8082

    server.vm.synced_folder "/", "/host"
    server.vm.synced_folder Dir.home, "/host_home"

    server.vm.provision "shell", name: "Enable cleartext passwords for SSH",
      keep_color: true,
      inline: <<-SHELL
        set -euo pipefail
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        systemctl restart sshd
      SHELL

    ansible_provision server,
      playbook="server_provision.yml",
      extra_vars: {
        "dummy": "test"
      }
  end

  config.vm.define :"client" do |client|
    client.vm.box = "ubuntu/focal64"
    client.vm.hostname = "client"
    client.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      vb.customize ["modifyvm", :id, "--uart1", "off"]
      vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    end

    client.vm.network "private_network", ip: "192.168.80.12",
      virtualbox__intnet: "vagrant-intnet"
    client.vm.network "forwarded_port", guest: 80, host: 8083
    client.vm.network "forwarded_port", guest: 443, host: 8084

    client.vm.synced_folder "/", "/host"
    client.vm.synced_folder Dir.home, "/host_home"

    client.vm.provision "shell", name: "Enable cleartext passwords for SSH",
      keep_color: true,
      inline: <<-SHELL
        set -euo pipefail
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        systemctl restart sshd
      SHELL

    ansible_provision client,
      playbook="client_provision.yml",
      extra_vars: {
        "dummy": "test"
      }
  end
end
