# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :host1 do |host1|
    host1.vm.box = "ubuntu/xenial64"
    host1.vm.hostname = "host1"
    host1.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      # vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
    host1.vm.network "private_network", ip: "192.168.199.10", virtualbox__intnet: "vagrant-intnet"
    # host1.vm.provision "shell", path: "provision-script.ps1"
  end

  config.vm.define :host2 do |host2|
    host2.vm.box = "cheretbe/win10_en_64"
    host2.winrm.username = "vagrant"
    host2.winrm.password = "#{ENV['AO_DEFAULT_VAGRANT_PASSWORD']}"
    host2.vm.boot_timeout = 600
    host2.vm.hostname = "host2"
    host2.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
    host2.vm.network "private_network", ip: "192.168.199.11", virtualbox__intnet: "vagrant-intnet"
    # host2.vm.provision "shell", path: "provision-script.ps1"
  end
end
